spring.application.name=DWI
server.port=8081

# 1. Configuración del Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Credenciales y URL dinámicas (Ocultas en variables de entorno)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# 3. Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 4. JWT Seguro
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000