spring.application.name=DWI
server.port=8081

# 1. Configuración del Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. La URL
# 2. La URL (Sin usuario ni contraseña incrustados)
spring.datasource.url=jdbc:postgresql://dpg-d7u1uvl7vvec73bcgjbg-a.oregon-postgres.render.com/clinica_glge
# 3. Tus credenciales de Render
spring.datasource.username=admin_clinica
spring.datasource.password=WgYtjUXmCrKkyJ0PAk0zziybszSfDhje

# 4. Hibernate: Para que cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# 5. Para que la consola te muestre el SQL que hace por debajo 
spring.jpa.show-sql=true

# 6. Esta es la "firma" de la clínica.
jwt.secret=ClaveSecretaClinicaRomeroParaElProyectoDWIQueDebeSerLarga2026!

# 7. Tiempo de expiración del token en milisegundos (86400000 ms = 24 horas)
jwt.expiration=86400000